trigger:
- master

jobs:
- job: Xcode_test
  strategy:
    maxParallel: 10
    matrix:
      # Previous iOS versions requires previous Xcode verisons, which isn't supported by TIMEncryptedStorage
      ios15:
        IMAGE_NAME: 'macOS-latest'
        XCODE_DEVELOPER_PATH: /Applications/Xcode_13.2.1.app
        IOS_SIMULATORS: 'iPhone 13 Pro,OS=15.2'
      
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
  - script: sudo xcode-select -switch $(XCODE_DEVELOPER_PATH)
    displayName: Select Xcode version
  
  - script: xcodebuild -version
    displayName: Xcode version

  - script: xcodebuild -scheme TIMEncryptedStorage -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$(IOS_SIMULATORS)' test
    displayName: 'xcodebuild test'
